[package]
name = "models"
version = "0.1.0"
authors = ["putchom <putchom8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
accelerometer = "0.12.0"
micromath = "2.0.0"
